# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/MIPS/MIPS.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/MIPS/MIPS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado_projects/MIPS/MIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/vivado_projects/test_env/test_env.srcs/sources_1/new/SSD.vhd
  D:/vivado_projects/test_env/test_env.srcs/sources_1/new/MPG.vhd
  D:/vivado_projects/MIPS/MIPS.srcs/sources_1/new/IF.vhd
  D:/vivado_projects/MIPS/MIPS.srcs/sources_1/new/MIPS.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/test_env/constrangeri.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/test_env/constrangeri.xdc]


synth_design -top MIPS -part xc7a35tcpg236-1


write_checkpoint -force -noxdef MIPS.dcp

catch { report_utilization -file MIPS_utilization_synth.rpt -pb MIPS_utilization_synth.pb }
