# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/EX/EX.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/EX/EX.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado_projects/EX/EX.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/vivado_projects/EX/EX.srcs/sources_1/new/EX.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top EX -part xc7a35tcpg236-1


write_checkpoint -force -noxdef EX.dcp

catch { report_utilization -file EX_utilization_synth.rpt -pb EX_utilization_synth.pb }
