# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/project_3/project_3.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/vivado_projects/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/vivado_projects/project_3/project_3.srcs/sources_1/new/Booth.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Booth -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Booth.dcp

catch { report_utilization -file Booth_utilization_synth.rpt -pb Booth_utilization_synth.pb }
